# Generated by Django 5.1.1 on 2024-09-25 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubric_assessment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rubric_assessment.rubric')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rubric_assessment.student')),
            ],
        ),
    ]
