# Generated by Django 5.1.1 on 2024-09-17 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='tasks',
        ),
        migrations.AlterField(
            model_name='session',
            name='activity_type',
            field=models.CharField(choices=[('Lab Exercise', 'Lab Exercise'), ('Assignment', 'Assignment'), ('Assessment', 'Assessment'), ('Project', 'Project'), ('MCQ', 'Multiple-Choice Questions (MCQs)'), ('Presentation', 'Presentation'), ('Workshop', 'Workshop'), ('Practical Lab', 'Practical Lab'), ('Quiz', 'Quiz'), ('Case Study', 'Case Study')], default='Lab Exercise', max_length=50),
        ),
        migrations.AlterField(
            model_name='session',
            name='demos',
            field=models.ManyToManyField(blank=True, limit_choices_to={'groups__name': 'Lab Assistant'}, related_name='lab_assistants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_title', models.CharField(max_length=255)),
                ('tasks', models.ManyToManyField(to='course.task')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.lesson'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TaskSession',
        ),
    ]
