# Generated by Django 5.1.1 on 2024-09-16 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_remove_course_course_fees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='total_duration',
        ),
    ]
