# Generated by Django 5.1.1 on 2024-09-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_remove_schedule_course_schedule_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='total_num_assesments',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='total_num_tasks',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
