# Generated by Django 5.1.1 on 2024-09-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_module_total_num_assesments_module_total_num_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='ojt_period_months',
        ),
        migrations.RemoveField(
            model_name='course',
            name='total_num_assesments',
        ),
        migrations.RemoveField(
            model_name='module',
            name='total_num_assesments',
        ),
        migrations.AddField(
            model_name='course',
            name='total_num_assessments',
            field=models.PositiveIntegerField(default=1, help_text='Total number of assessments across modules'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='total_num_assessments',
            field=models.PositiveIntegerField(default=1, help_text='Total number of assessments for this module'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='practical_hours',
            field=models.PositiveIntegerField(help_text='Total practical hours for the course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='theory_hours',
            field=models.PositiveIntegerField(help_text='Total theory hours for the course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='total_num_modules',
            field=models.PositiveIntegerField(help_text='Total number of modules'),
        ),
        migrations.AlterField(
            model_name='course',
            name='total_num_tasks',
            field=models.PositiveIntegerField(help_text='Total number of tasks across modules'),
        ),
        migrations.AlterField(
            model_name='module',
            name='total_num_tasks',
            field=models.PositiveIntegerField(help_text='Total number of tasks for this module'),
        ),
        migrations.AlterField(
            model_name='module',
            name='total_practical_hours',
            field=models.PositiveIntegerField(help_text='Total practical hours for this module'),
        ),
        migrations.AlterField(
            model_name='module',
            name='total_theory_hours',
            field=models.PositiveIntegerField(help_text='Total theory hours for this module'),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_theory',
            field=models.BooleanField(default=True, help_text='Is this a theory task?'),
        ),
    ]
