# Generated by Django 5.1.1 on 2024-09-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_remove_course_ojt_period_months_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='curriculum_availability',
            field=models.BooleanField(default=True, help_text='Is the curriculum available? (Yes/No)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='curriculum_category',
            field=models.CharField(choices=[('nvq', 'NVQ'), ('nonnvq', 'Non-NVQ'), ('nie', 'NIE'), ('other', 'Other')], help_text='Select curriculum category', max_length=50),
        ),
    ]
