# Generated by Django 5.1.1 on 2024-09-17 07:34

import course.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=20, unique=True)),
                ('course_title', models.CharField(max_length=200)),
                ('course_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck if the course is inactive')),
                ('theory_hours', models.PositiveIntegerField(help_text='Total theory hours for the course')),
                ('practical_hours', models.PositiveIntegerField(help_text='Total practical hours for the course')),
                ('assignment_hours', models.PositiveIntegerField(default=0, help_text='Total hours for assignments/projects')),
                ('total_num_modules', models.PositiveIntegerField(help_text='Total number of modules')),
                ('total_num_assessments', models.PositiveIntegerField(help_text='Total number of assessments across modules')),
                ('total_num_tasks', models.PositiveIntegerField(help_text='Total number of tasks across modules')),
                ('duration_months', models.PositiveIntegerField(help_text='Course duration in months (without OJT)')),
                ('entry_qualification', models.CharField(help_text='Entry qualification required', max_length=100)),
                ('medium', models.CharField(choices=[('English', 'English'), ('Sinhala', 'Sinhala'), ('Tamil', 'Tamil')], max_length=50)),
                ('delivery_mode', models.CharField(choices=[('Classroom', 'Classroom'), ('Online', 'Online'), ('Blended', 'Blended')], max_length=50)),
                ('course_mode', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], max_length=50)),
                ('curriculum_category', models.CharField(choices=[('nvq', 'NVQ'), ('nonnvq', 'Non-NVQ'), ('nie', 'NIE'), ('other', 'Other')], help_text='Select curriculum category', max_length=50)),
                ('curriculum_availability', models.BooleanField(default=True, help_text='Is the curriculum available? (Yes/No)')),
                ('batches_per_year', models.PositiveIntegerField(help_text='Number of batches per annum')),
                ('capacity_per_batch', models.PositiveIntegerField(help_text='Number of students per batch')),
                ('course_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tools_available', models.TextField(blank=True, help_text='List of tools available')),
                ('equipment_available', models.TextField(blank=True, help_text='List of equipment available')),
                ('machinery_available', models.TextField(blank=True, help_text='List of machinery available')),
                ('industry_sector', models.CharField(help_text='Select industry/sector', max_length=100)),
                ('equivalent_course', models.CharField(blank=True, help_text='Equivalent course (if any)', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SessionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_duration_minutes', models.PositiveIntegerField(help_text='Maximum duration allowed for a session in minutes')),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('min_students', models.PositiveIntegerField(validators=[course.models.validate_min_students])),
                ('max_students', models.PositiveIntegerField(validators=[course.models.validate_max_students])),
                ('demos', models.ManyToManyField(blank=True, limit_choices_to={'groups__name': 'Lab Assistant'}, related_name='demo_batches', to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(blank=True, limit_choices_to={'groups__name': 'Student'}, related_name='enrolled_batches', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(limit_choices_to={'groups__name': 'Teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_batches', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_present', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.batch')),
            ],
        ),
        migrations.CreateModel(
            name='CompletedModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=100)),
                ('date_completed', models.DateField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.batch')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompletedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('date_completed', models.DateField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.batch')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CoursePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.batch')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=255)),
                ('total_theory_hours', models.PositiveIntegerField(help_text='Total theory hours for this module')),
                ('total_practical_hours', models.PositiveIntegerField(help_text='Total practical hours for this module')),
                ('total_num_assessments', models.PositiveIntegerField(help_text='Total number of assessments for this module')),
                ('total_num_tasks', models.PositiveIntegerField(help_text='Total number of tasks for this module')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.batch')),
                ('module_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.module')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('Theory', 'Theory'), ('Practical', 'Practical')], default='Theory', max_length=10)),
                ('session_date', models.DateField(default=django.utils.timezone.now)),
                ('start_time', models.TimeField(default=django.utils.timezone.now)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('activity_type', models.CharField(default='Lab Exercise', max_length=50)),
                ('attendance', models.PositiveIntegerField(help_text='Number of students attending this session')),
                ('additional_notes', models.TextField(blank=True, help_text='Additional session notes, observations, or comments')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('demos', models.ManyToManyField(blank=True, limit_choices_to={'groups__name': 'Lab Assistant'}, related_name='lab_assistant', to=settings.AUTH_USER_MODEL)),
                ('trainer_name', models.ForeignKey(limit_choices_to={'groups__name': 'Teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='training', to=settings.AUTH_USER_MODEL)),
                ('session_setting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.sessionsetting')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('total_hours', models.PositiveIntegerField(help_text='Total hours for this task')),
                ('learning_objectives', models.TextField(blank=True, help_text='What students will learn', null=True)),
                ('teaching_activities', models.TextField(blank=True, help_text='Teaching activities for the task', null=True)),
                ('resources', models.TextField(blank=True, help_text='Required resources and materials', null=True)),
                ('assessment_activities', models.TextField(blank=True, help_text='Assessment activities to evaluate student learning', null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.module')),
            ],
        ),
        migrations.CreateModel(
            name='TaskSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_minutes', models.PositiveIntegerField(help_text='Duration spent on this task within the session')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.session')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.task')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='tasks',
            field=models.ManyToManyField(through='course.TaskSession', to='course.task'),
        ),
    ]
