# Generated by Django 5.1.1 on 2024-09-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_session_tasks_alter_session_activity_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='activity_type',
        ),
        migrations.AddField(
            model_name='lesson',
            name='activity_type',
            field=models.CharField(choices=[('Lab Exercise', 'Lab Exercise'), ('Assignment', 'Assignment'), ('Assessment', 'Assessment'), ('Project', 'Project'), ('MCQ', 'Multiple-Choice Questions (MCQs)'), ('Presentation', 'Presentation'), ('Workshop', 'Workshop'), ('Practical Lab', 'Practical Lab'), ('Quiz', 'Quiz'), ('Case Study', 'Case Study')], default='Lab Exercise', max_length=50),
        ),
    ]
