# Generated by Django 5.1.1 on 2024-09-23 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_remove_activity_end_time_remove_activity_start_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingRubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('max_points', models.FloatField()),
                ('points_awarded', models.FloatField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubrics', to='course.activity')),
            ],
        ),
    ]
