# Generated by Django 5.1.1 on 2024-09-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_gradingrubric'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='submission',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
