# Generated by Django 5.1.1 on 2024-09-14 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher'), ('Lab Assistant', 'Lab Assistant')], max_length=20)),
                ('nic_passport_no', models.CharField(max_length=30, verbose_name='NIC/Passport No.')),
                ('contact_address', models.TextField(verbose_name='Contact Address')),
                ('permanent_address', models.TextField(blank=True, null=True, verbose_name='Permanent Address')),
                ('mobile_no', models.CharField(max_length=15, verbose_name='Mobile No.')),
                ('home_no', models.CharField(blank=True, max_length=15, null=True, verbose_name='Home Telephone')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
