# Generated by Django 5.1.1 on 2024-09-19 05:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('exercise_title', models.CharField(max_length=100)),
                ('submission_deadline', models.DateTimeField()),
                ('submission_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_on_time', models.CharField(default='Pending', max_length=20)),
                ('level_of_completion', models.CharField(max_length=20)),
                ('quality_of_work', models.IntegerField()),
                ('learning_outcome', models.TextField()),
                ('challenges', models.TextField(blank=True, null=True)),
                ('teacher_feedback', models.TextField(blank=True, null=True)),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
