# Generated by Django 5.1.1 on 2024-09-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='submission_deadline',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='completed_on_time',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='submission_time',
            field=models.DateTimeField(),
        ),
    ]
