# Generated by Django 5.1.1 on 2024-09-22 13:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corusemgt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='deadline',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
