"""Add status column to Exercise table

Revision ID: 002cae0d6992
Revises: 
Create Date: 2024-09-19 10:21:24.234447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002cae0d6992'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.alter_column('rating',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('status')

    # ### end Alembic commands ###
