"""Add status column to Exercise table1

Revision ID: 59dac8f6a34b
Revises: 002cae0d6992
Create Date: 2024-09-19 10:46:23.907936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59dac8f6a34b'
down_revision = '002cae0d6992'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submission_deadline', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('submission_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('grade', sa.Integer(), nullable=True))
        batch_op.drop_column('rating')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.INTEGER(), nullable=True))
        batch_op.drop_column('grade')
        batch_op.drop_column('submission_time')
        batch_op.drop_column('submission_deadline')

    # ### end Alembic commands ###
